## set TEMP_NUM before calling
## if TEMP_NUM = 1 then the entries for TEMP_NUM 1 in this IOC will be used for the setup

stringiftest("FULL_AUTO_PRESSURE", "$(FULL_AUTO_PRESSURE_$(TEMP_NUM)=)")

## Load our record instances
$(IFFULL_AUTO_PRESSURE) dbLoadRecords("db/MercuryFullAuto.db", "P=$(MYPVPREFIX)$(IOCNAME):,TEMP_CARD=$(TEMP_NUM),PRESSURE_CARD=$(FULL_AUTO_PRESSURE_$(TEMP_NUM)=),RECSIM=$(RECSIM),DISABLE=$(DISABLE),TEMP_DEADBAND=$(FULL_AUTO_TEMP_DEADBAND=0.0),MIN_PRESSURE=$(FULL_AUTO_MIN_PRESSURE=),MAX_PRESSURE=$(FULL_AUTO_MAX_PRESSURE=),OFFSET=$(FULL_AUTO_OFFSET=),OFFSET_DURATION=$(FULL_AUTO_OFFSET_DURATION=),TIMEPV=$(MYPVPREFIX)CS:IOC:$(IOCNAME):DEVIOS:GTIM_TIME,GAIN=$(FULL_AUTO_GAIN=)")

dbLoadRecords("db/MercuryFullAutoAvailable.db", "P=$(MYPVPREFIX)$(IOCNAME):,TEMP_CARD=$(TEMP_NUM),IFFULL_AUTO_PRESSURE=$(IFFULL_AUTO_PRESSURE)")
